# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c1ac84fcfcfda9d328c02646865a45082fd3fc4afd51c168c40401ca77ea3cde79c95271cd874b9c3798d16ab5ae24d3c5e9c6842a08c8491c6a0559f5bffea

test:
  secret_key_base: e31aa092c2e740c3d24d87f3f7b85bf8c62dd49c7cc205fa562f16a806e310f4ce249ab07ae55cfd5be2de4629e3f0cf11c6aebf66126094ee91a3a41d9b00dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
